### ISSUE TITLE
./configure no exist

### ISSUE THREAD

**Issue by ff-rm** [danomatika/rc-unitd#10]
Hi, how are you?

When i run the ./autogen.sh the console say this
configure.ac:30: error: possibly undefined macro: AC_CHECK_INCLUDES_DEFAULT
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /usr/bin/autoconf failed with exit status: 1

what i miss?

**Comment by danomatika** [comment]
If that works for you, can you close the issue?

**Comment by ff-rm** [comment]
Yes. Is working well. Thanks
